In [71]:
import pandas as pd

In [72]:
df = pd.read_csv('../src/AMD_EnhanceMacdNum01.csv')
df_live = pd.read_csv('../src/AMD_live.csv')

In [73]:
obj = pd.to_datetime('2023-01-20 14:30:00')
df.datetime = pd.to_datetime(df.datetime)
df_live.datetime = pd.to_datetime(df_live.datetime)

df = df[df.datetime > obj]
df_live = df_live[df_live.datetime > obj]

In [74]:
cols = df.columns

In [75]:
obj = pd.to_datetime('2023-01-20 16:15:00')


df = df[df.datetime<= obj][cols]
df_live = df_live[df_live.datetime<= obj][cols]

In [76]:
df.head()

,datetime,MACD,MACD_H,MACD_S,open,high,low,close,volume,SlowMACD,FastMACD,Slow,ATR,sig
454,2023-01-20 14:45:00,-0.052962,0.026970,-0.079933,68.190,68.335,67.78,68.1501,2086012,-0.274554,-0.027830,68.031962,0.469382,0
455,2023-01-20 15:00:00,-0.043692,0.028992,-0.072684,68.160,68.400,67.97,68.1600,1358057,-0.242608,-0.032584,68.056667,0.463756,0
456,2023-01-20 15:15:00,-0.047877,0.019846,-0.067723,68.170,68.200,67.54,68.0600,1706147,-0.210228,-0.041088,68.086905,0.491791,0
457,2023-01-20 15:30:00,-0.044334,0.018711,-0.063045,68.070,68.360,68.07,68.1000,1445009,-0.178896,-0.049913,68.115000,0.464392,0
458,2023-01-20 15:45:00,-0.044975,0.014456,-0.059431,68.105,68.290,68.01,68.0621,1018441,-0.151612,-0.053783,68.123190,0.438051,0

In [77]:
df_live.head()

,datetime,MACD,MACD_H,MACD_S,open,high,low,close,volume,SlowMACD,FastMACD,Slow,ATR,sig
38,2023-01-20 14:45:00,-0.052972,0.026987,-0.079959,68.190,68.335,67.78,68.1501,2086012,-0.274614,-0.027847,68.031962,0.469386,0
39,2023-01-20 15:00:00,-0.043701,0.029006,-0.072707,68.160,68.400,67.97,68.1600,1358057,-0.242660,-0.032598,68.056667,0.463760,0
40,2023-01-20 15:15:00,-0.047884,0.019858,-0.067743,68.170,68.200,67.54,68.0600,1706147,-0.210274,-0.041100,68.086905,0.491794,0
41,2023-01-20 15:30:00,-0.044341,0.018722,-0.063062,68.070,68.360,68.07,68.1000,1445009,-0.178935,-0.049923,68.115000,0.464395,0
42,2023-01-20 15:45:00,-0.044981,0.014465,-0.059446,68.105,68.290,68.01,68.0621,1018441,-0.151646,-0.053792,68.123190,0.438053,0